name:                hopl3
version:             0.1.0.0
github:              "githubuser/hopl3"
license:             CC-BY-NC-3.0
author:              "Matthew A Johnson"
maintainer:          "Matt.Johnson@marist.edu"
copyright:           "2015-2020 Matthew A Johnson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hopl3#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1

library:
  source-dirs: src

executables:
  hopl3-repl:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is repl
    dependencies:
    - hopl3
    - mtl >= 2.2
    - haskeline >= 0.7

  hopl3-run:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is run
    dependencies:
    - hopl3
    - mtl >= 2.2
    - haskeline >= 0.7

tests:
  hopl3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hopl3
    - mtl >= 2.2
    - haskeline >= 0.7
    - tasty
    - tasty-hunit
    - tasty-hspec
